force touch whenever a credential is deleted
Nitrokey/trussed-secrets-app pull request #93
Opened 2023-06-27 21:05 UTC by peterwilli

This fixes https://github.com/Nitrokey/trussed-secrets-app/issues/92

It's my first try-out on the NitroKey firmware, open to feedback!

What I did was:

- See if I can get the fake NitroKey working over USB/IP as instructed here: https://github.com/Nitrokey/trussed-secrets-app/issues/92#issuecomment-1609962949
- Run the tests
- Apply the fix (I checked how the button press was used in other parts of the code)
- Re-run the tests, observe touch response in logs

2023-06-27 21:25 UTC, szszszsz commented
Nice! I hope it was a pleasant exercise :-)

Re topic, I think we should use `self.user_present()` directly instead though, to unconditionally check for the touch button input. This would be similar to how register command handles that, and would follow the design table.

The idea here is to decrease the chance for the potential DOS attack execution success.

2023-06-27 21:27 UTC, szszszsz requested changes
Let's use `self.user_present()?;` instead for the unconditional user presence check, at the beginning of the function.

2023-06-27 22:10 UTC, peterwilli commented
> Re topic, I think we should use `self.user_present()` directly instead though, to unconditionally check for the touch button input. This would be similar to how register command handles that, and would follow the design table.

Thanks for the kind words! And yeah it was an awesome exercise. When I saw the bug I immediately realized that it was opportunity calling.

I think I see what the change does now. By calling `user_present` directly, one will get a button press confirmation screen all the time. `require_touch_if_needed` only does it if your key is in the pin-protected area (I think)

2023-06-27 22:20 UTC, peterwilli commented
I made a change now that uses purely `user_present` and re-ran the test and it worked fine. 

I simply used `nitropy nk3 secrets add-password test && nitropy nk3 secrets remove test` to see if there was a button press log during the remove part.

2023-06-28 07:40 UTC, robin-nitrokey approved these changes

2023-06-28 07:43 UTC, szszszsz commented
Looks good! Please squash the commits and we are ready to go.

2023-06-28 08:55 UTC, peterwilli commented
@szszszsz the commits have been squashed into 1, I also made the message more clear

2023-06-28 09:58 UTC, szszszsz commented
> Thanks! I'm sorry, it's a habit not to squash commits during PR review for me. I'll do that now!

Very good habit, please maintain it :-)
It allows to check are the requested changes in line with the expectations.

2023-06-28 10:13 UTC, peterwilli commented
> > Thanks! I'm sorry, it's a habit not to squash commits during PR review for me. I'll do that now!
> 
> Very good habit, please maintain it :-) It allows to check are the requested changes in line with the expectations.

Thank you!

Also, thanks for letting me do this, this was very great introduction. I'm well aware that his thing would've been done much quicker if you did it yourself, so thanks for your time showing me virtually around!

I'm looking forward to doing more next time.

2023-06-28 10:21 UTC, merged

2023-06-28 10:24 UTC, peterwilli commented
> Yup! Perfect problem to kick off some work. Thank you for the help! If you would like to do some more, you can write down some quick development notes from this experience (or correct existing, if there are any). It would be valuable since it is written from the POV of the person just familiarizing oneself with the project. No need to make it ideal - we will improve that on the way.

What would development notes be in this case? The main time spent was on setting up the right development environment (USB/IP, etc). The fix was in the end 1 line.

2023-06-28 10:33 UTC, szszszsz commented
I was thinking here about the encountered problems with the environment setup (if you had any), or trouble recognizing the code structure. Personally I think setting the simulation up and running, and pytest's test execution from pynitrokey are not well described (the details I've passed in the original ticket). 
Feel free to skip it too, if you find something else more interesting.

We have something along these lines here for the Nitrokey 3:
- https://github.com/Nitrokey/nitrokey-3-firmware/tree/main/docs

2023-06-28 15:00 UTC, peterwilli commented
> I was thinking here about the encountered problems with the environment setup (if you had any), or trouble recognizing the code structure. Personally I think setting the simulation up and running, and pytest's test execution from pynitrokey are not well described (the details I've passed in the original ticket). Feel free to skip it too, if you find something else more interesting.
> 
> We have something along these lines here for the Nitrokey 3:
> 
> * https://github.com/Nitrokey/nitrokey-3-firmware/tree/main/docs

Thanks for the guidelines. I might be able to, I have a better idea of what you're after. I'm currently occupied with installing a matrix homeserver (and failing hard at doing so) but after that I'll get back to it.